In [1]:
import pandas as pd
import numpy as np

In [2]:
ala=pd.read_csv('Airbus.csv')

In [4]:
ala

,Nights,AIMSID,NAME,Fleet,base,Position,FlightDate,FlightNo,FlightPostfix,DepartureAirport,ARR,STD,STA,CrewType,INTL_LAYOVER_TIME,LAYOVER_TIME
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:50,23:50
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:50,23:50
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,ALA,PEK,980,1255,FlightDeck,23:15,23:15
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:45,23:45
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:20,23:20
5,0,661,NEKRASSOV ANATOLIY ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:45,23:45
6,0,661,NEKRASSOV ANATOLIY ...,320,ALA,CP,00:00.0,911,,ALA,IST,715,1085,FlightDeck,23:25,23:25
7,0,768,MUSTAFIN RAFKAT ...,320,ALA,CP,00:00.0,937,,URA,FRA,430,710,FlightDeck,18:30,18:30
8,0,774,SADYKOV SAMAT ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:29,23:29
9,0,776,KIRCHU BORIS ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:30,23:30
10,0,835,DADISHEV LEONID ...,320,ALA,FO,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:50,23:50
11,0,835,DADISHEV LEONID ...,320,ALA,FO,00:00.0,267,,ALA,PEK,980,1255,FlightDeck,23:10,23:10
12,0,835,DADISHEV LEONID ...,320,ALA,FO,00:00.0,135,,ALA,LED,735,1060,FlightDeck,14:00,14:00
13,0,870,ABDUKARIMOV SERGEY ...,320,ALA,FO,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:50,23:50
14,0,870,ABDUKARIMOV SERGEY ...,320,ALA,FO,00:00.0,267,,ALA,PEK,980,1255,FlightDeck,23:15,23:15
15,0,1447,KHEGAY VYACHESLAV ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:50,23:50
16,0,1447,KHEGAY VYACHESLAV ...,320,ALA,CP,00:00.0,267,,ALA,PEK,980,1255,FlightDeck,23:15,23:15
17,0,1447,KHEGAY VYACHESLAV ...,320,ALA,CP,00:00.0,135,,ALA,LED,735,1060,FlightDeck,22:35,22:35
18,0,1447,KHEGAY VYACHESLAV ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:25,23:25
19,0,2008,ARTEMENKO MIKHAIL ...,320,ALA,CP,00:00.0,267,,ALA,PEK,980,1255,FlightDeck,22:25,22:25
20,0,2008,ARTEMENKO MIKHAIL ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:25,23:25
21,0,2360,SAGANDYKOV MARSEL ...,320,ALA,FO,00:00.0,135,,ALA,LED,735,1060,FlightDeck,14:40,14:40
22,0,2489,BAIKHOJAYEV AMANGELDY ...,320,ALA,FO,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:25,23:25
23,0,2490,AKHMETOV GABIT ...,320,ALA,CP,00:00.0,135,,ALA,LED,735,1060,FlightDeck,14:40,14:40
24,0,2490,AKHMETOV GABIT ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:30,23:30
25,0,2661,SHUKEVICH VLADISLAV ...,320,ALA,CP,00:00.0,267,,ALA,PEK,980,1255,FlightDeck,"23,82","23,82"
26,0,2661,SHUKEVICH VLADISLAV ...,320,ALA,CP,00:00.0,267,,ALA,PEK,980,1255,FlightDeck,23:50,23:50
27,0,3185,TUNLIKBAYEV DAUREN ...,320,ALA,CP,00:00.0,135,,ALA,LED,735,1060,FlightDeck,"23,47","23,47"
28,0,3185,TUNLIKBAYEV DAUREN ...,320,ALA,CP,00:00.0,135,,ALA,LED,735,1060,FlightDeck,23:25,23:25
29,0,3481,TSOY PAVEL ...,320,ALA,FO,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:45,23:45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,2,10340,SKRIBACHEV VADIM ...,320,ALA,FO,00:00.0,911,,ALA,IST,715,1085,FlightDeck,48:55:00,48:55:00
276,2,96385,TOPP HANSGEORG ...,320,ALA,FO,00:00.0,911,,ALA,IST,715,1085,FlightDeck,48:10:00,48:10:00
277,2,96385,TOPP HANSGEORG ...,320,ALA,FO,00:00.0,401,,ALA,KBP,710,1025,FlightDeck,48:45:00,48:45:00
278,2,96521,NIKOLOV GEORGI ...,320,ALA,CP,00:00.0,135,,ALA,LED,735,1060,FlightDeck,48:10:00,48:10:00
279,2,96521,NIKOLOV GEORGI ...,320,ALA,CP,00:00.0,401,,ALA,KBP,710,1025,FlightDeck,48:45:00,48:45:00
280,2,96521,NIKOLOV GEORGI ...,320,ALA,CP,00:00.0,405,,ALA,KBP,55,390,FlightDeck,58:35:00,58:35:00
281,2,96536,PETROV NIKOLAY ...,320,ALA,CP,00:00.0,903,,GUW,AMS,135,460,FlightDeck,49:35:00,49:35:00
282,2,96536,PETROV NIKOLAY ...,320,ALA,CP,00:00.0,153,,ALA,LED,135,460,FlightDeck,56:35:00,56:35:00
283,2,96543,STOJANOVIC NENAD ...,320,ALA,CP,00:00.0,903,,GUW,AMS,135,460,FlightDeck,49:30:00,49:30:00
284,3,229,URAZAKOV ARTUR ...,320,ALA,CP,00:00.0,903,,GUW,AMS,135,460,FlightDeck,73:30:00,73:30:00
285,3,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,903,,GUW,AMS,135,460,FlightDeck,"73,07","73,07"
286,3,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,903,,GUW,AMS,135,460,FlightDeck,73:05:00,73:05:00
287,3,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,405,,ALA,KBP,55,390,FlightDeck,83:00:00,83:00:00
288,3,2360,SAGANDYKOV MARSEL ...,320,ALA,FO,00:00.0,903,,GUW,AMS,135,460,FlightDeck,72:43:00,72:43:00
289,3,2490,AKHMETOV GABIT ...,320,ALA,CP,00:00.0,947,,GUW,FRA,20,330,FlightDeck,78:15:00,78:15:00
290,3,2661,SHUKEVICH VLADISLAV ...,320,ALA,CP,00:00.0,947,,GUW,FRA,20,330,FlightDeck,78:05:00,78:05:00
291,3,3776,YELEUOV YERMEK ...,320,ALA,FO,00:00.0,947,,GUW,FRA,20,330,FlightDeck,78:15:00,78:15:00
292,3,4077,TURYSBEKOV ARMAN ...,320,ALA,CP,00:00.0,903,,GUW,AMS,135,460,FlightDeck,73:15:00,73:15:00
293,3,5180,RESHETNIKOV ALEXANDR ...,320,ALA,CP,00:00.0,947,,GUW,FRA,20,330,FlightDeck,78:15:00,78:15:00
294,3,5394,ISSAYEV SAYAN ...,320,ALA,FO,00:00.0,947,,GUW,FRA,20,330,FlightDeck,78:05:00,78:05:00
295,3,5623,BEKEYEV ASHIR ...,320,ALA,CP,00:00.0,947,,GUW,FRA,20,330,FlightDeck,78:05:00,78:05:00
296,3,6520,LAPOCHKIN ALEXANDR ...,320,ALA,FO,00:00.0,947,,GUW,FRA,20,330,FlightDeck,78:05:00,78:05:00
297,3,6533,SEBEKOV YERZHAN ...,320,ALA,FO,00:00.0,903,,GUW,AMS,135,460,FlightDeck,73:30:00,73:30:00
298,3,6837,SAKENOV ILYAS ...,320,ALA,FO,00:00.0,947,,GUW,FRA,20,330,FlightDeck,"78,18","78,18"
299,3,6837,SAKENOV ILYAS ...,320,ALA,FO,00:00.0,947,,GUW,FRA,20,330,FlightDeck,78:10:00,78:10:00
300,3,7549,BYZHIBEKOV TALGAT ...,320,ALA,FO,00:00.0,947,,GUW,FRA,20,330,FlightDeck,78:15:00,78:15:00
301,3,8141,DUDINOV VALERIY ...,320,ALA,FO,00:00.0,903,,GUW,AMS,135,460,FlightDeck,73:15:00,73:15:00
302,3,9069,ZHARKOV ROMAN ...,320,ALA,FO,00:00.0,903,,GUW,AMS,135,460,FlightDeck,73:05:00,73:05:00
303,3,96385,TOPP HANSGEORG ...,320,ALA,FO,00:00.0,405,,ALA,KBP,55,390,FlightDeck,83:00:00,83:00:00
304,3,96640,PANIC IGOR ...,320,ALA,CP,00:00.0,903,,GUW,AMS,135,460,FlightDeck,73:05:00,73:05:00

In [3]:
ala.head()

,Nights,AIMSID,NAME,Fleet,base,Position,FlightDate,FlightNo,FlightPostfix,DepartureAirport,ARR,STD,STA,CrewType,INTL_LAYOVER_TIME,LAYOVER_TIME
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:50,23:50
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:50,23:50
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,ALA,PEK,980,1255,FlightDeck,23:15,23:15
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:45,23:45
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,ALA,DME,775,1070,FlightDeck,23:20,23:20

In [7]:
ala.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305 entries, 0 to 304
Data columns (total 16 columns):
Nights               305 non-null int64
AIMSID               305 non-null int64
NAME                 305 non-null object
Fleet                305 non-null int64
base                 305 non-null object
Position             305 non-null object
FlightDate           305 non-null object
FlightNo             305 non-null int64
FlightPostfix        305 non-null object
DepartureAirport     305 non-null object
ARR                  305 non-null object
STD                  305 non-null int64
STA                  305 non-null int64
CrewType             305 non-null object
INTL_LAYOVER_TIME    305 non-null object
LAYOVER_TIME         305 non-null object
dtypes: int64(6), object(10)
memory usage: 38.2+ KB

In [4]:
ala.drop(['DepartureAirport', 'CrewType', 'INTL_LAYOVER_TIME'],axis=1, inplace=True)

In [5]:
ala.head()

,Nights,AIMSID,NAME,Fleet,base,Position,FlightDate,FlightNo,FlightPostfix,ARR,STD,STA,LAYOVER_TIME
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:15
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20

In [6]:
ala.rename(columns=lambda x:x.replace('_','').lower(), inplace=True)

In [11]:
ala.head()

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr,std,sta,layovertime
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:15
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20

In [16]:
ala.aimsid.unique()

array([   41,    97,   547,   626,   661,   768,   774,   776,   835,
         870,  1447,  2008,  2360,  2489,  2490,  2661,  3185,  3481,
        3522,  3776,  4359,  4599,  5178,  5180,  5294,  5295,  5337,
        5394,  5454,  5623,  5738,  5964,  6391,  6533,  6607,  7014,
        7354,  7549,  7573,  7574,  8077,  8140,  8141,  8142,  8149,
        9069,  9105,  9584,  9644,  9647, 10340, 10585, 96385, 96456,
       96499, 96503, 96506, 96521, 96536,    76,   226,   229,   498,
         781,   884,  1269,  2045,  2077,  4077,  4358,  4600,  6145,
        6520,  6679,  6837,  7281,  7355,  8143,  9106, 10221, 95042,
       96324, 96389, 96500, 96543, 96628, 96640, 96680])

In [7]:
ala[ala['aimsid']==41]

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr,std,sta,layovertime
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50
230,2,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,903,,AMS,135,460,49:20:00
231,2,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,153,,LED,135,460,57:35:00

In [7]:
ala.arr.unique()

array(['DME ', 'PEK ', 'IST ', 'FRA ', 'LED ', 'KBP ', 'AMS ', 'DXB '],
      dtype=object)

In [8]:
ala.groupby('aimsid')['arr'].value_counts()

aimsid  arr
41      DME     2
        AMS     1
        LED     1
76      KBP     2
        PEK     1
97      PEK     1
226     KBP     1
        LED     1
229     AMS     2
        IST     1
        LED     1
498     KBP     1
        LED     1
547     AMS     2
        DME     1
        IST     1
        LED     1
626     DME     1
        KBP     1
        LED     1
        PEK     1
661     DME     1
        IST     1
        KBP     1
        LED     1
768     PEK     2
        FRA     1
        LED     1
774     DME     1
776     KBP     3
               ..
96324   IST     2
96385   DME     2
        KBP     2
        IST     1
        PEK     1
96389   PEK     1
96456   IST     1
96499   IST     2
96500   IST     1
96503   DME     1
        LED     1
        PEK     1
96506   IST     2
        FRA     1
        KBP     1
96521   KBP     2
        DME     1
        LED     1
        PEK     1
96536   AMS     1
        DME     1
        IST     1
        KBP     1
        LED     1
96543   AMS     1
        IST     1
96628   IST     1
96640   AMS     2
96680   AMS     1
        PEK     1
Name: arr, Length: 248, dtype: int64

In [10]:
ala.arr.str.strip()

0      DME
1      DME
2      PEK
3      DME
4      DME
5      DME
6      IST
7      FRA
8      DME
9      DME
10     DME
11     PEK
12     LED
13     DME
14     PEK
15     DME
16     PEK
17     LED
18     DME
19     PEK
20     DME
21     LED
22     DME
23     LED
24     DME
25     PEK
26     PEK
27     LED
28     LED
29     DME
      ...
275    IST
276    IST
277    KBP
278    LED
279    KBP
280    KBP
281    AMS
282    LED
283    AMS
284    AMS
285    AMS
286    AMS
287    KBP
288    AMS
289    FRA
290    FRA
291    FRA
292    AMS
293    FRA
294    FRA
295    FRA
296    FRA
297    AMS
298    FRA
299    FRA
300    FRA
301    AMS
302    AMS
303    KBP
304    AMS
Name: arr, Length: 305, dtype: object

In [9]:
ala.head()

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr,std,sta,layovertime
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:15
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20

In [25]:
ala.arr.unique()

array(['DME ', 'PEK ', 'IST ', 'FRA ', 'LED ', 'KBP ', 'AMS ', 'DXB '],
      dtype=object)

In [10]:
dme=ala[ala['arr'].str.strip()=='DME']
dme

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr,std,sta,layovertime
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20
5,0,661,NEKRASSOV ANATOLIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45
8,0,774,SADYKOV SAMAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:29
9,0,776,KIRCHU BORIS ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:30
10,0,835,DADISHEV LEONID ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:50
13,0,870,ABDUKARIMOV SERGEY ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:50
15,0,1447,KHEGAY VYACHESLAV ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50
18,0,1447,KHEGAY VYACHESLAV ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:25
20,0,2008,ARTEMENKO MIKHAIL ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:25
22,0,2489,BAIKHOJAYEV AMANGELDY ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:25
24,0,2490,AKHMETOV GABIT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:30
29,0,3481,TSOY PAVEL ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:45
30,0,3522,YESSIN ALEXANDR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:05
31,0,3776,YELEUOV YERMEK ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:50
32,0,3776,YELEUOV YERMEK ...,320,ALA,FO,00:00.0,875,,DME,775,1070,22:51
33,0,4359,TAYUSHEV ALEXEY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20
34,0,4599,ZHAKENOV AIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,22:51
36,0,5178,PAVLOVA POLINA ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:25
37,0,5180,RESHETNIKOV ALEXANDR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45
38,0,5294,SHAIKEN MADIYAR ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:30
41,0,5295,TATARENKO LEONID ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:10
43,0,5394,ISSAYEV SAYAN ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:40
48,0,5738,BELYAYEV YEVGENIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:25
49,0,5964,BEKEYEV AMANGELDY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20
50,0,6391,ALEKEYEV ELDAR ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:30
52,0,6607,ISSAK DANIYAR ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:20
57,0,7354,IBRAYEV YERZHAN ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:30
59,0,7573,KOZHALIYEV YELNAR ...,320,ALA,FO,00:00.0,875,,DME,775,1070,20:30
60,0,7573,KOZHALIYEV YELNAR ...,320,ALA,FO,00:00.0,875,,DME,775,1070,"23,67"
61,0,7573,KOZHALIYEV YELNAR ...,320,ALA,FO,00:00.0,875,,DME,775,1070,"23,73"
62,0,7573,KOZHALIYEV YELNAR ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:40
63,0,7574,TURMATOV YERNUR ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:29
66,0,8077,ABILBEKOV DIAS ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:25
67,0,8140,KOTOROV PETR ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:50
71,0,8141,DUDINOV VALERIY ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:55
76,0,9584,ALZHANOV MADI ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:50
77,0,9644,GALIYEV FUAT ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:45
79,0,9644,GALIYEV FUAT ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:10
83,0,10585,SHAPAREV VLADISLAV ...,320,ALA,FO,00:00.0,875,,DME,775,1070,"23,35"
84,0,10585,SHAPAREV VLADISLAV ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:22
85,0,96385,TOPP HANSGEORG ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:05
86,0,96385,TOPP HANSGEORG ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:20
89,0,96503,IVANOV IVAN ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:40
93,0,96536,PETROV NIKOLAY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,20:30
110,1,884,USTINOV VLADIMIR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,26:25:00
144,1,5295,TATARENKO LEONID ...,320,ALA,CP,00:00.0,875,,DME,775,1070,24:00:00
147,1,5337,OLKHOVSKIY STANISLAV ...,320,ALA,FO,00:00.0,875,,DME,775,1070,24:00:00
171,1,7355,TOKTAROV YERNAR ...,320,ALA,FO,00:00.0,875,,DME,775,1070,26:25:00
175,1,7549,BYZHIBEKOV TALGAT ...,320,ALA,FO,00:00.0,875,,DME,775,1070,24:00:00
222,1,96521,NIKOLOV GEORGI ...,320,ALA,CP,00:00.0,875,,DME,775,1070,24:00:00

In [12]:
dme.arr.unique()

array(['DME '], dtype=object)

In [11]:
res_dme=dme.groupby('aimsid')['arr'].value_counts()

In [12]:
res_dme.head()

aimsid  arr
41      DME     2
547     DME     1
626     DME     1
661     DME     1
774     DME     1
Name: arr, dtype: int64

In [15]:
ala.merge(res_dme, on ='aimsid', how='left')

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr_x,std,sta,layovertime,arr_y
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2.0
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2.0
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:15,NaN
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45,1.0
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20,1.0
5,0,661,NEKRASSOV ANATOLIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45,1.0
6,0,661,NEKRASSOV ANATOLIY ...,320,ALA,CP,00:00.0,911,,IST,715,1085,23:25,1.0
7,0,768,MUSTAFIN RAFKAT ...,320,ALA,CP,00:00.0,937,,FRA,430,710,18:30,NaN
8,0,774,SADYKOV SAMAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:29,1.0
9,0,776,KIRCHU BORIS ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:30,1.0
10,0,835,DADISHEV LEONID ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:50,1.0
11,0,835,DADISHEV LEONID ...,320,ALA,FO,00:00.0,267,,PEK,980,1255,23:10,1.0
12,0,835,DADISHEV LEONID ...,320,ALA,FO,00:00.0,135,,LED,735,1060,14:00,1.0
13,0,870,ABDUKARIMOV SERGEY ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:50,1.0
14,0,870,ABDUKARIMOV SERGEY ...,320,ALA,FO,00:00.0,267,,PEK,980,1255,23:15,1.0
15,0,1447,KHEGAY VYACHESLAV ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2.0
16,0,1447,KHEGAY VYACHESLAV ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:15,2.0
17,0,1447,KHEGAY VYACHESLAV ...,320,ALA,CP,00:00.0,135,,LED,735,1060,22:35,2.0
18,0,1447,KHEGAY VYACHESLAV ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:25,2.0
19,0,2008,ARTEMENKO MIKHAIL ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,22:25,1.0
20,0,2008,ARTEMENKO MIKHAIL ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:25,1.0
21,0,2360,SAGANDYKOV MARSEL ...,320,ALA,FO,00:00.0,135,,LED,735,1060,14:40,NaN
22,0,2489,BAIKHOJAYEV AMANGELDY ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:25,1.0
23,0,2490,AKHMETOV GABIT ...,320,ALA,CP,00:00.0,135,,LED,735,1060,14:40,1.0
24,0,2490,AKHMETOV GABIT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:30,1.0
25,0,2661,SHUKEVICH VLADISLAV ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,"23,82",NaN
26,0,2661,SHUKEVICH VLADISLAV ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:50,NaN
27,0,3185,TUNLIKBAYEV DAUREN ...,320,ALA,CP,00:00.0,135,,LED,735,1060,"23,47",NaN
28,0,3185,TUNLIKBAYEV DAUREN ...,320,ALA,CP,00:00.0,135,,LED,735,1060,23:25,NaN
29,0,3481,TSOY PAVEL ...,320,ALA,FO,00:00.0,875,,DME,775,1070,23:45,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,2,10340,SKRIBACHEV VADIM ...,320,ALA,FO,00:00.0,911,,IST,715,1085,48:55:00,NaN
276,2,96385,TOPP HANSGEORG ...,320,ALA,FO,00:00.0,911,,IST,715,1085,48:10:00,2.0
277,2,96385,TOPP HANSGEORG ...,320,ALA,FO,00:00.0,401,,KBP,710,1025,48:45:00,2.0
278,2,96521,NIKOLOV GEORGI ...,320,ALA,CP,00:00.0,135,,LED,735,1060,48:10:00,1.0
279,2,96521,NIKOLOV GEORGI ...,320,ALA,CP,00:00.0,401,,KBP,710,1025,48:45:00,1.0
280,2,96521,NIKOLOV GEORGI ...,320,ALA,CP,00:00.0,405,,KBP,55,390,58:35:00,1.0
281,2,96536,PETROV NIKOLAY ...,320,ALA,CP,00:00.0,903,,AMS,135,460,49:35:00,1.0
282,2,96536,PETROV NIKOLAY ...,320,ALA,CP,00:00.0,153,,LED,135,460,56:35:00,1.0
283,2,96543,STOJANOVIC NENAD ...,320,ALA,CP,00:00.0,903,,AMS,135,460,49:30:00,NaN
284,3,229,URAZAKOV ARTUR ...,320,ALA,CP,00:00.0,903,,AMS,135,460,73:30:00,NaN
285,3,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,903,,AMS,135,460,"73,07",1.0
286,3,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,903,,AMS,135,460,73:05:00,1.0
287,3,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,405,,KBP,55,390,83:00:00,1.0
288,3,2360,SAGANDYKOV MARSEL ...,320,ALA,FO,00:00.0,903,,AMS,135,460,72:43:00,NaN
289,3,2490,AKHMETOV GABIT ...,320,ALA,CP,00:00.0,947,,FRA,20,330,78:15:00,1.0
290,3,2661,SHUKEVICH VLADISLAV ...,320,ALA,CP,00:00.0,947,,FRA,20,330,78:05:00,NaN
291,3,3776,YELEUOV YERMEK ...,320,ALA,FO,00:00.0,947,,FRA,20,330,78:15:00,2.0
292,3,4077,TURYSBEKOV ARMAN ...,320,ALA,CP,00:00.0,903,,AMS,135,460,73:15:00,NaN
293,3,5180,RESHETNIKOV ALEXANDR ...,320,ALA,CP,00:00.0,947,,FRA,20,330,78:15:00,1.0
294,3,5394,ISSAYEV SAYAN ...,320,ALA,FO,00:00.0,947,,FRA,20,330,78:05:00,1.0
295,3,5623,BEKEYEV ASHIR ...,320,ALA,CP,00:00.0,947,,FRA,20,330,78:05:00,NaN
296,3,6520,LAPOCHKIN ALEXANDR ...,320,ALA,FO,00:00.0,947,,FRA,20,330,78:05:00,NaN
297,3,6533,SEBEKOV YERZHAN ...,320,ALA,FO,00:00.0,903,,AMS,135,460,73:30:00,NaN
298,3,6837,SAKENOV ILYAS ...,320,ALA,FO,00:00.0,947,,FRA,20,330,"78,18",NaN
299,3,6837,SAKENOV ILYAS ...,320,ALA,FO,00:00.0,947,,FRA,20,330,78:10:00,NaN
300,3,7549,BYZHIBEKOV TALGAT ...,320,ALA,FO,00:00.0,947,,FRA,20,330,78:15:00,1.0
301,3,8141,DUDINOV VALERIY ...,320,ALA,FO,00:00.0,903,,AMS,135,460,73:15:00,1.0
302,3,9069,ZHARKOV ROMAN ...,320,ALA,FO,00:00.0,903,,AMS,135,460,73:05:00,NaN
303,3,96385,TOPP HANSGEORG ...,320,ALA,FO,00:00.0,405,,KBP,55,390,83:00:00,2.0
304,3,96640,PANIC IGOR ...,320,ALA,CP,00:00.0,903,,AMS,135,460,73:05:00,NaN

In [13]:
DME_FULL=ala.merge(res_dme, on ='aimsid', how='left')

In [14]:
DME_FULL.head()

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr_x,std,sta,layovertime,arr_y
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2.0
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2.0
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:15,NaN
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45,1.0
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20,1.0

In [102]:
DME_FULL=DME_FULL.rename(columns={"arr_y":"DME"})

In [105]:
DME_FULL.head()

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr_x,std,sta,layovertime,DME
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2.0
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2.0
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:15,NaN
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45,1.0
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20,1.0

In [20]:
##заменить нан на 0 
##convert float na int
#delete duplicates

ala.head(5)

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr,std,sta,layovertime
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:15
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20

In [106]:
DME_FULL=DME_FULL.fillna(0)

In [109]:
DME_FULL.head()

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr_x,std,sta,layovertime,DME
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2.0
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2.0
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:15,0.0
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45,1.0
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20,1.0

In [111]:
DME_FULL=DME_FULL.astype({"DME":"int32"})

In [121]:
PEK=ala[ala['arr'].str.strip()=='PEK']

In [124]:
PEK=PEK.groupby('aimsid')['arr'].value_counts()

In [125]:
PEK=PEK.fillna(0)

In [126]:
PEK.head()

aimsid  arr
76      PEK     1
97      PEK     1
626     PEK     1
768     PEK     2
835     PEK     1
Name: arr, dtype: int64

In [127]:
DME_PEK=DME_FULL.merge(PEK, on ='aimsid', how='left')

In [128]:
DME_PEK.head()

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr_x,std,sta,layovertime,DME,arr
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2,NaN
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2,NaN
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:15,0,1.0
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45,1,NaN
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20,1,1.0

In [129]:
DME_PEK.count()

nights           305
aimsid           305
name             305
fleet            305
base             305
position         305
flightdate       305
flightno         305
flightpostfix    305
arr_x            305
std              305
sta              305
layovertime      305
DME              305
arr              132
dtype: int64

In [130]:
DME_PEK=DME_PEK.fillna(0)

In [131]:
DME_PEK= DME_PEK.astype({"arr":"int32"})

In [132]:
DME_PEK.head()

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr_x,std,sta,layovertime,DME,arr
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2,0
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2,0
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:15,0,1
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45,1,0
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20,1,1

In [136]:
DME_PEK=DME_PEK.rename(columns={"arr":"PEK"})

In [138]:
DME_PEK.head()

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr_x,std,sta,layovertime,DME,PEK
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2,0
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2,0
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:15,0,1
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45,1,0
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20,1,1

In [140]:
IST=ala[ala['arr'].str.strip()=='IST']

In [141]:
IST.head()

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr,std,sta,layovertime
6,0,661,NEKRASSOV ANATOLIY ...,320,ALA,CP,00:00.0,911,,IST,715,1085,23:25
39,0,5294,SHAIKEN MADIYAR ...,320,ALA,FO,00:00.0,911,,IST,715,1085,22:55
47,0,5738,BELYAYEV YEVGENIY ...,320,ALA,CP,00:00.0,911,,IST,715,1085,22:30
51,0,6533,SEBEKOV YERZHAN ...,320,ALA,FO,00:00.0,911,,IST,715,1085,23:20
64,0,7574,TURMATOV YERNUR ...,320,ALA,FO,00:00.0,911,,IST,715,1085,23:25

In [143]:
IST=IST.groupby('aimsid')['arr'].value_counts()

In [145]:
IST.head()

aimsid  arr
229     IST     1
547     IST     1
661     IST     1
776     IST     1
781     IST     1
Name: arr, dtype: int64

In [147]:
DME_PEK_IST=DME_PEK.merge(IST, on ='aimsid', how='left')

In [150]:
DME_PEK_IST=DME_PEK_IST.fillna(0)

In [151]:
DME_PEK_IST.head()

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr_x,std,sta,layovertime,DME,PEK,arr
0,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2,0,0.0
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2,0,0.0
2,0,97,SATBALDIYEV ADIL ...,320,ALA,CP,00:00.0,267,,PEK,980,1255,23:15,0,1,0.0
3,0,547,STULBO GENNADIY ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:45,1,0,1.0
4,0,626,BEKEYEV ZHANAIDAR ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:20,1,1,0.0

In [153]:
DME_PEK_IST=DME_PEK_IST.astype({"arr":"int32"})

In [155]:
DME_PEK_IST[DME_PEK_IST.duplicated()]

,nights,aimsid,name,fleet,base,position,flightdate,flightno,flightpostfix,arr_x,std,sta,layovertime,DME,PEK,arr
1,0,41,ZHILISBAYEV MARAT ...,320,ALA,CP,00:00.0,875,,DME,775,1070,23:50,2,0,0

In [159]:
DME_PEK_IST=DME_PEK_IST.drop_duplicates()